const smalltalkQuestions = [
  "Ich hätte gern mehr privaten Kontakt in unserem Team. Wie gehst du auf die Kolleginnen und Kollegen zu?",
  "Was machst du eigentlich in deinem Sommerurlaub? Fährst du weg?",
  "Ich sieze meine Vorgesetzten lieber. Kannst du dir vorstellen, deinen Chef oder deine Chefin zu duzen?",
  "Ich singe jetzt in einem Chor. Was machst du gern in deiner Freizeit?",
  "Heute spielt FC Bayern gegen Borussia Dort- mund. Interessierst du dich auch für Fußball?",
  "Wie war denn dein Wochenende? Hast du etwas Schönes unternommen?",
  "Ich muss heute früher gehen, weil die Kita meiner Tochter früher schließt. Hast du auch Kinder?",
  "In der Kantine gibt es jetzt auch ein Salat-Büfett. Was isst du mittags am liebsten?",
  "Ich hätte gern flexible Arbeitszeiten. Wann musst du morgens anfangen?",
  "Hast du Pläne für das Wochenende, guckst du Fußball?",
  "Ich stehe jeden Morgen im Stau. Das nervt mich total. Kommst du auch mit dem Auto zur Arbeit?",
  "Was findest du besser: einmal im Jahr einen langen Urlaub machen oder mehrmals einen Kurzurlaub?",
  "Ich würde gerne im Home-Office  arbeiten. Könntest du dir das auch vorstellen?",
  "Hast du Vorschläge für unseren  Betriebsausflug? Wohin würdest du gerne fahren?",
  "Ich würde gern mehr im Team arbeiten. Wie siehst du das?",
  "Was könnte man am Wochenende mit den Kollegen gemeinsam unternehmen?",
  "Das Essen in der Kantine ist schrecklich. Wo könnte man mittags noch essen?",
  "Hast du eigentlich schon Pläne für den Urlaub?",
  "Würdest du gern in Teilzeit arbeiten?",
  "Frau da Costa geht nächste Woche in Rente. Was könnte man ihr zum Abschied schenken?",
  "Ich pendle täglich über eine Stunde mit dem Bus zur Arbeit. Wie sieht es bei dir aus?",
  "Was machst du im Sommer, hast du schon Pläne für den Urlaub?",
  "Ich hätte gern Gleitzeit. Du auch?",
  "Ich interessiere mich in meiner Freizeit sehr für Fußball, du auch?",
  "Was machst du denn abends, treibst du Sport?",
  "Ich würde gerne eine Weiterbildung machen. Welche hast du schon gemacht?",
  "Ich möchte gerne mal die Kolleginnen und Kollegen zu mir nach Hause einladen. Lädst du manchmal Kollegen zur dir ein?",
  "Seit ich ein Kind habe, merke ich, dass Beruf und Privatleben gar nicht so einfach zu vereinbaren sind. Welche Erfahrungen hast du damit gemacht?",
  "Mit Filmen kann ich mich richtig gut entspannen. Wie entspannst du am besten von der Arbeit?",
  "Ich arbeite gerne mit anderen im Team. Welche Erfahrungen hast du damit gemacht?",
  "Ich nehme mir den Brückentag frei. Was machst du an dem Tag?",
  "Ich stehe morgens oft im Stau. Wie fährst du zur Arbeit?",
  "Für mich ist Arbeit mehr als nur Geld verdienen, sie muss Spaß machen. Wie ist das bei dir?",
  "Ich würde gern mobil arbeiten: zu Hause, am See, im Garten. Hast du schon mal mobil gearbeitet?",
  "Was machst du in deinem Urlaub? Verreist du?",
  "Du arbeitest doch schon länger hier. Kannst du mir ein gutes Restaurant in der Nähe empfehlen?",
  "Ich mache zurzeit einen Englischkurs an der VHS. Welche Fremdsprachen sprichst du eigentlich?",
  "Der Bus hatte heute 15 Minuten Verspätung. Fast wäre ich zu spät gekommen. Wie kommst du zur Arbeit?",
  "Hallo. Du bist ja wieder aus dem Urlaub zurück. Wie war es denn?",
  "Was machst du gern in deiner Freizeit?",
  "Nach dem Mittagessen brauche ich einen Espresso. Trinken Sie auch so gern Kaffee?",
  "Ich finde die Idee, Hunde an den Arbeitsplatz mitzubringen, gut. Und du?",
  "Hast du schon gehört? Unser Betriebsausflug fällt dieses Jahr aus. Die Firma muss wahrscheinlich sparen.",
  "Ich muss heute länger arbeiten, weil wir viele neue Kunden haben. Machst du auch manchmal Überstunden?",
  "Ich arbeite manchmal ganz gerne am Wochenende. Und du?",
  "Unternimmst du gerne in der Freizeit etwas mit den Kollegen?",
  "Wir arbeiten bald alle in einem Großraumbüro, Ich stelle mir das nicht so angenehm vor. Was meinst du?",
  "Ich bringe mir häufig Essen von zu Hause mit und bleibe an meinem Schreibtisch. Wie verbringst du normalerweise deine Mittagspause?",
  "Dieses Jahr machen wir keinen Urlaub im Heimatland, wir bleiben in Deutschland. Wie findest Du das?",
  "Wie findest Du, wenn wir Fahrgemeinschaften bilden und zusammen zur Arbeit fahren würden?",
  "Was ist besser für Dich, Freizeit mit der Familie zu verbringen oder mit den Kollegen?",
  "Meine Tochter ist bald drei Jahre alt und wir suchen für sie eine Leih-Oma oder einen Leih-Opa. Kannst du mir eine Agentur nennen, die sich darauf spezialisiert? Oder vielleicht kennst du jemanden, der in diesem Bereich tätig ist?",
  "Als Nichtraucherin habe ich ein Problem damit, dass mehrere unserer Kollegen fast einmal die Stunde rausgehen und rauchen. Manchmal brauche ich schnell die Meinung oder Hilfe von diesen Kollegen und muss dann warten, bis sie von der Raucherpause zurückkommen. Was würdest du an meiner Stelle tun, wie würdest du reagieren?",
  "Wie du weißt, findet im nächsten Monat der Stadtmarathon statt. Unser Abteilungsleiter will unbedingt, dass wir alle dabei sind. Ich habe keine Lust darauf, wie siehst du es? Nimmst du daran teil?",
  "Wie du weißt, fanden in den letzten Monaten ziemlich intensive Verhandlungen zwischen unserem Betriebsrat und unseren Chefs statt. Leider wird es auch im nächsten Jahr keine Lohnerhöhung geben, und dies bei der hohen Inflation. Wie findest du das?",
  "Mein Sohn ist auf dem Gymnasium und er muss zwei Wochen lang ein Betriebspraktikum absolvieren. Ich bin unsicher, ob ich ihn zu uns in die Firma einladen soll, oder ob es besser ist, wenn er eine andere Firma kennenlernt. Was denkst du?",
  "Mein kleiner Sohn geht jetzt in den Kindergarten Ich muss ihn morgens hinbringen und schaffe es nicht, um 8 Uhr pünktlich im Büro zu sein. Ich würde gern meinen Chef fragen, ob ich jeden Morgen eine halbe Stunde später anfangen darf und traue mich nicht, es zu tun. Hast du einen Rat für mich?",
  "Unser Chef hat mich heute gefragt, ob ich die Organisation der nächsten Wochenendklausur für alle leitenden Mitarbeiter übernehmen möchte. Ich habe keine Zeit und keine Lust dazu, möchte unseren Chef aber nicht enttäuschen. Was und wie soll ich ihm antworten? Hast du eine Idee?",
  "Unser neuer Mitarbeiter mischt sich in alles ein und gibt uns allen Ratschläge, auch ohne dass man ihn gefragt hat. Mich ärgert das auf die Dauer. Wie findest du es? Ich würde es gerne ansprechen, nur wie?",
  "Bei dem derzeitigen Preisanstieg für alles frage ich mich, ob ich meine Arbeitskleidung weiterhin in der Reinigung waschen und bügeln lassen soll. Eigentlich ist es mir jetzt zu teuer. Wie siehst du das?",
  "Da ich keine Kinder habe, bekomme ich meinen Urlaub nie im Sommer genehmigt. Ich finde das mittlerweile unangenehm und unfair. Wie siehst du es?",
  "Hast du schon den nächsten Urlaub geplant? Bist du auf die: Schulferien angewiesen?",
  "Soweit ich weiß, arbeitest du Vollzeit. Du hast doch ein Kind, wie machst du das? Wie schaffst du das alles?",
  "Wie du weißt, bin ich in unserer Firma neu. Wie ist es hier eigentlich mit der Krankmeldung geregelt?",
  "Wie du weißt, ist am nächsten Freitag unsere Weihnachtsfeier. Was ziehst du an?",
  "Ich soll am nächsten Sonntag arbeiten.Es ist ein verkaufsoffener Sonntag. Meinst du, ich bekomme dafür in den nächsten Wochen einen anderen Tag frei?",
  "Ich habe morgen meine erste Nachtschicht. Ich mache mir jetzt schon Sorgen, ob ich die ganze Zeit wach bleiben kann. Wie schaffst du es eigentlich, dass du wach bleibst?",

  "Unser Team bekommt nächste Woche Verstärkung. Kennst du die neue Kollegin schon?",
  "Heute war der Verkehr wirklich zäh. Kommst du auch mit der Bahn?",
  "In Deutschland muss man oft viele Formulare ausfüllen. Gibt es in deinem Heimatland auch so viel Bürokratie?",
  "Manchmal ist es gar nicht so leicht, Familie und Beruf unter einen Hut zu bringen. Was ist dir wichtiger – Familie oder Karriere?",
  "Nächsten Monat findet der Firmenlauf statt. Wirst du auch teilnehmen?",
  "Unsere Teammeetings finden seit einiger Zeit jede Woche statt. Findest du das zu häufig? Was hältst du davon?",
  "Ich habe in letzter Zeit viele Überstunden gemacht. Was meinst du – ist es besser, sie auszahlen zu lassen oder lieber Freizeitausgleich zu nehmen?",
  "Nach der Arbeit bin ich oft müde. Wie kann man sich trotz Familie und vielen Familienangelegenheiten gut erholen?",
  "Ich verbringe meine Mittagspause gern außerhalb des Betriebs. Wie ist das bei dir – wo machst du am liebsten Pause?",
  "Ich habe noch fünf Tage Resturlaub. Weißt du, was eigentlich mit dem Resturlaub passiert, wenn man ihn nicht nimmt?",
  "Unser Chef möchte, dass wir die Arbeitsunfähigkeitsbescheinigung schon ab dem ersten Krankheitstag abgeben. Was hältst du davon?",
  "Ich möchte meinen nächsten Urlaub gern in Deutschland verbringen. Was kannst du mir empfehlen?",
  "Ein Kollege kommt fast jeden Tag zu spät zur Arbeit. Wie findest du das?",
  "Einmal im Monat treffen sich einige Kollegen zum Stammtisch nach der Arbeit. Gehst du auch manchmal hin?",
  "Bald findet wieder unsere Betriebsfeier statt. Manche Kollegen kommen mit Partner oder Partnerin, andere lieber allein. Was hältst du davon?",
  "In den Ferien bleiben viele Familien in der Stadt. Welche Aktivitäten gibt es hier für Kinder?",
  "Viele Menschen möchten heute ihr eigenes Geschäft starten. Denkst du, es ist eine gute Idee, sich selbstständig zu machen?",
  "In unserer Firma gibt es eine dreimonatige Kündigungsfrist. Findest du das gut oder zu lang?",
  "Ich soll am Samstag für eine Kollegin einspringen. Weißt du, ob ich dafür nächste Woche einen anderen Tag frei bekomme?",
  "Ich plane eine längere Fahrradtour. Hast du so etwas schon einmal gemacht?",
  "Bevorzugst du bargeldlose Zahlungen?",
  "Nächste Woche veranstalte ich eine Einweihungsparty. Könntest du mir bei der Vorbereitung helfen?",
  "Einige Kollegen nehmen am Firmenlauf teil – machst du auch mit?",
  "Wöchentliche Mini-Meetings – sind sie zu häufig?",
  "Ich habe einen Freund, der bis 14 arbeitet. Was denkst du darüber?",
  "Ich beginne bald eine Nachtschicht. Welchen Rat können Sie mir geben?",
  "Ich muss einem Kollegen an seinem freien Tag helfen. Bekomme ich dafür einen Tag frei?",
  "Ausbildung beginnt am Wochenende, liegt der freie Tag an einem anderen Tag?",
  "Ich wurde von einem Freund zu einer Radtour eingeladen, hatte es aber noch nie ausprobiert. Und du?",
  "Jeden Tag fahre ich 45 Minuten mit dem Zug zur Arbeit und es macht mir Spaß, wie geht es dir?",
  "Was macht ihr während der Ferien mit den Kindern in der Stadt?",
  "Wie nutzt du die 5 Tage vom letzten Jahr?",
  "Die Kantine wurde für eine Weile geschlossen, was sagst du dazu?",
  "Was denkst du, braucht man alle zwei Jahre ein neues Handy?",
  "In der Kantine gibt es jetzt auch ein Salat-Büfett. Was isst du mittags am liebsten?",
  "Ich muss heute früher gehen, weil die Kita meiner Tochter früher schließt. Hast du auch Kinder?",
  "Hast du deinen Urlaub schon geplant? Du hast schulpflichtige Kinder und bist auf die Ferien angewiesen.",
  "Sie arbeiten Vollzeit und haben Kinder. Wie schaffen Sie es, Beruf und Familie unter einen Hut zu bringen?",
  "Wie stehst du zu Brückentagen? Nutzt du sie, um einen Kurzurlaub zu machen, oder findest du es besser, normal zu arbeiten?",
  "Was hältst du davon, dass wir verpflichtende Computerkurse machen müssen und dafür 50 Euro im Monat von unserem Gehalt abgezogen wird? Findest du das fair?",
  "Wohin würden Sie eine Familienreise empfehlen? Haben Sie einen Tipp für ein gutes Reiseziel, das für Kinder geeignet ist?",
  "Wie stehen Sie dazu, zusätzlich am Arbeitsplatz zu lernen oder sich weiterzubilden? Halten Sie das für notwendig oder eher überflüssig?",
  "Hast du Ideen, was man im Sommer in der Stadt unternehmen kann? Welche Aktivitäten kannst du empfehlen?",
  "Hast du schon eine Idee, was wir morgen Abend mit den Kollegen unternehmen könnten? Hast du Vorschläge?",
  "Findest du, dass in der Kantine mehr vegane Gerichte angeboten werden sollten? Würdest du sie ausprobieren oder isst du lieber klassische Gerichte?",
  "Was findest du besser: Homeoffice oder Büroarbeit? Wo arbeitest du produktiver und fühlst dich wohler?",
  "Ich überlege, im Herbst Urlaub zu nehmen. Was hältst du davon? Ist es eine gute Idee, in dieser Jahreszeit frei zu nehmen?",
  "Ich überlege, mit ehrenamtlicher Arbeit anzufangen. Hast du eine Idee, wie man am besten damit startet?",
  "Was halten Sie von Frühschichten? Sind Sie eher ein Frühaufsteher oder fällt es Ihnen schwer, so früh zu arbeiten?",
  "Wie entspannen Sie sich nach der Arbeit am besten? Haben Sie eine Lieblingsmethode, um abzuschalten?",
  "Wie schaffst du es, die Balance zwischen Freizeit und Arbeit zu halten? Hast du Tipps, wie man das besser managen kann?",
  "Was denkst du, sollte man an den Betriebsausflügen teilnehmen? Findest du solche Events wichtig?",
  "Wo isst du lieber zu Mittag – im Büro oder draußen? Und isst du lieber alleine oder mit Kollegen?",
  "Ich muss jeden Tag 45 Minuten im Zug verbringen. Hast du Ideen, was man in dieser Zeit Sinnvolles tun könnte?",
  "Ich bin mir unsicher, was ich zur Party mit den Kollegen anziehen soll. Hast du eine Idee, was passend wäre?",
  "Die Ausgaben sind in letzter Zeit stark gestiegen. Hast du Ideen, wie man das Einkommen erhöhen könnte, um damit klarzukommen?",
  "Wie stehen Sie zu Gesundheitsvorsorge-Veranstaltungen? Denken Sie, dass solche Angebote im Unternehmen wichtig sind?",
  "Ich plane einen Umzug und brauche einen guten Handwerker. Hast du eine Idee, wo ich jemanden finden könnte, der zuverlässig ist?",
  "Findest du es eine gute Idee, einen Partner zur Firmenfeier mitzubringen? Oder sollte man lieber alleine hingehen?",
  "Hast du dir schon Gedanken gemacht, wohin du im nächsten Urlaub fahren möchtest?",
  "Das Essen in der Kantine ist nicht besonders gut. Wo gehst du normalerweise in der Mittagspause essen?",
  "Hast du schon mal von Bildungsurlaub gehört? Was hältst du davon, während der Arbeit eine Woche für Weiterbildung freizunehmen?",
  "Ich überlege, einen Teilzeitjob anzunehmen. Was denkst du darüber? Hast du selbst schon mal Teilzeit gearbeitet?",
  "Wie findest du es, wenn Praktikanten Überstunden machen müssen? Denkst du, das ist fair oder nicht? Was ist deine Meinung dazu?",
  "Ich habe gesehen, dass es in der Kantine jetzt nur noch abgepackte Brötchen gibt. Was denkst du darüber?",
  "Ich habe gehört, dass einige Kollegen in der Pause Tischtennis spielen. Wie findest du das? Würdest du auch mitspielen?",
  "Sie haben sich beim Mittagessen mit einem Kollegen getroffen und besprechen, welche ungesunden Lebensmittel im Café des Unternehmens angeboten werden.",
  "Reinigungsfirma hat das Büro nicht gut gereinigt.",
  "Es war uns verboten, private Mobiltelefone zu benutzen. Sie können nur während einer Pause verwendet werden.",
  "Ich möchte meine Kollegen besser kennenlernen, aber ich bin mir nicht sicher, wie ich das am besten anstellen soll.",
  "Mein Kind weint immer, wenn ich es in die Kita bringe. Ich weiß nicht, was ich tun soll.",
  "Hast du Pläne für das Wochenende, guckst du Fußball?",
  "Ich hätte gern flexible Arbeitszeiten. Wann musst du morgens anfangen?",
  "In unserer Firma wird der Tag der offenen Tür und wir können unsere Kinder mitbringen.",
  "Unsere Firma plant, ein Sommerfest zu veranstalten, jedoch wird in diesem Jahr keine Weihnachtsfeier stattfinden. Diskutieren Sie mit Ihrem Gesprächspartner am Arbeitsplatz über diese Entscheidung und tauschen Sie Ihre Gedanken zu den Gründen und möglichen Auswirkungen aus.",
  "Unsere Firma plant, E-Bikes für alle Mitarbeiter zu kaufen. Führen Sie ein informelles Gespräch am Arbeitsplatz darüber, indem Sie die Vorteile und möglichen Herausforderungen dieser Idee diskutieren.",
  "In der Firma gibt es keine festen Büros mehr. Mitarbeiter können jeden Tag wählen, wo sie arbeiten möchten.",
  "Sie planen einen Umzug und haben festgestellt, dass Ihnen ein Tag dafür nicht ausreicht. Sie fühlen sich gestresst und überfordert mit der Menge an Arbeit, die erledigt werden muss.",
  "Sie haben in einem Forum etwas zum Thema „Berufswahl\" gelesen. Berichten Sie Ihrem Partner / Ihrer Partnerin, welche Informationen Sie haben.",
  "Sie planen einen Umzug und haben festgestellt, dass Ihnen ein Tag dafür nicht ausreicht. Sie fühlen sich gestresst und überfordert mit der Menge an Arbeit, die erledigt werden muss.",
  "Seit ich ein Kind habe, merke ich, dass Beruf und Privatleben gar nicht so einfach zu vereinbaren sind. Welche Erfahrungen hast du damit gemacht?",
  "Ich arbeite bis 14:00 Uhr und mache Feierabend und du?",
  "Wir möchten am Wochenende grillen im Garten mit Freunden.",
  "Ich arbeite seit vielen Jahren in einem Unternehmen. Ich will mich weiterentwickeln. Was würden Sie mir empfehlen?",
  "Sie haben vorher ein Seminar gegen Stress besucht. Ich möchte auch eine Stressseminar für die Stressbewältigung. Was empfiehlst du?",
  "In den Pausen können die Mitarbeiter Tischtennis spielen.",
  "In der Betriebskantine wird kein warmes Essen zubereitet, sondern nur Brötchen gebacken.",
  "Nach der Arbeit wird man müde. Wovon hängt das ab? Wie gehe ich damit um?",
  "Jeden Freitag wollen die Kollegen nach der Arbeit zum Fußball-Gucken in die Sportsbar gehen. Jetzt soll ich auch mit. Was denkst du?",
  "Viele Menschen essen mittlerweile nur vegetarisch oder vegan. Auch in unserer Kantine gibt es immer weniger Gerichte mit Fleisch. Wie findest du das?",
  "Ab nächsten Monat müssen die Mitarbeiter Parkgebühren zahlen, wenn sie ihren Wagen auf dem Firmenparkplatz parken. Wirst du trotzdem zur Arbeit mit dem Auto kommen?",
  "In Deutschland sagt man: „Über Geld spricht man nicht\". Bei uns ist es aber kein Problem, mit Kolleginnen und Kollegen über das Gehalt zu sprechen. Und wie ist es bei euch?",
  "Meine Tochter geht seit Jahren zum Schwimmen im Sportverein. Nun möchte sie im Verein auch Fußball spielen. Ist es nicht zu viel für ein 10-jähriges Mädchen?",
  "Seitdem ich im Homeoffice bin, habe ich das Gefühl, 24 Stunden ununterbrochen zu arbeiten. Welche Erfahrungen hast du damit?",
  "Meist fahre ich zur Arbeit mit dem Fahrrad. Wenn es regnet, nehme ich den Bus. Nun überlege ich es mir, ein ÖPNV-Abo zu kaufen. Hast du so ein Abo?",
  "Ich arbeite gem mit anderen im Team. Welche Erfahrungen hast du damit gemacht?",
  "Arbeitest du lieber mit jüngeren oder älteren Kollegen und Kolleginnen zusammen?",
  "Ich hoffe sehr, dass ich im Juli Urlaub nehmen kann, obwohl ich keine Kinder habe. Wie ist es bei dir?",
  "Normalerweise fahre ich 45 Minuten zur Arbeit. Am Abend bin ich fix und fertig. Wie sieht es bei dir aus?",
  "Wäschst du selbst deine Arbeitskleidung zu Hause oder lässt du sie reinigen?",
  "Einige Kollegen nehmen ihre Elektroroller ins Büro mit, anstatt sie draußen stehen zu lassen. Ich finde das nicht in Ordnung. Wie siehst du das?",
  "Der letzte Betriebsausflug war richtig toll. Hast du Ideen, was wir bei unserem nächsten Ausflug unternehmen können?",
  "Ich wurde gefragt, ob ich am nächsten Wochenende arbeiten möchte. Dafür bekomme ich einen Wochenendzuschlag. Ich wollte aber am Wochenende mit der Familie wegfahren. Was soll ich nun machen?",
  "Ich muss am nächsten Samstag arbeiten. Meinst du, dass ich nächste Woche einen Tag frei nehmen kann?",
  "Morgen habe ich meine erste Nachtschicht. Was hilft dir wach zu bleiben?",
  "Wenn ich morgens ins Büro komme, stehen meistens auf meinem Arbeitsplatz dreckige Kaffeebecher. Können die Kollegen sie nicht in die Küche bringen, bevor sie Feierabend machen?",
  "Morgens muss ich meine Kinder in die Schule bringen und würde gern die Arbeit erst um 9:00 Uhr anfangen. Wie kann ich den Chef darauf ansprechen?",
  "Unser Chef möchte für die Mitarbeiter Dienstfahrräder Kaufen. Glaubst du, dass wir sie privat nutzen dürfen?",
  "Letztes Wochenende war ich mit meiner Familie im Kino. Wir haben uns einen ganz tollen Film angeschaut. Was machst du mit deiner Familie am Wochenende?",
  "Am nächsten Samstag findet eine Ganztagsfortbildung zur Bedienung neuer Technik statt. Bist du dabei?",
  "Unser Chef plant, bald überall Wasserspender aufzustellen. Dafür sollen wir monatlich 10 Euro bezahlen. Was hältst du davon?",
  "Mein Sohn ist bald 2 Jahre alt. Wir suchen für ihn einen zweisprachigen Kindergartenplatz. Kannst du mir vielleicht einen guten Kindergarten empfehlen?",
  "Seit einigen Jahren lebe ich in Deutschland, kann mich aber immer noch an das kalte Klima gewöhnen. Wie ist es bei dir?",
  "Hast du gehört, dass wir ab September dieses Jahres mehr Überstunden machen sollen und auch am Wochenende arbeiten müssen? Wie siehst du das?",
  "Mein Sohn wünscht sich zum Geburtstag einen Hund oder ein anderes Tier. Kennst du dich da aus?",
  "Hast du gehört, obwohl wir letztes Jahr so viele Überstunden gemacht und sehr gute Leistungen erbracht haben, bekommen wir keine Gehaltserhöhung. Was denkst du darüber?",
  "Wir dürfen ab sofort in den Pausen nicht mehr am Computer unsere persönlichen E-Mails checken, Was hältst du davon?",
  "In zwei Wochen ist der Stadtmarathon. Unsere Abteilung will unbedingt daran teilnehmen. Bist du dabei?",
  "Ich habe zurzeit viele Probleme mit unserem Kollegen Herrn Schulz. Hättest du einen Lösungsvorschlag, wie ich mein Arbeitsverhältnis mit ihm verbessern kann?",
  "Seit zwei Wochen jogge ich wieder morgens. Danach fühle ich mich den ganzen Tag wohler. Was machst du für deine Gesundheit?",
  "Sollen wir eine E-Mail an alle Mitarbeiter senden, um Geld für ein gemeinsames Geschenk zur Feier des 25-jährigen Firmenjubiläums unseres Kollegen Herrn Müller zu sammeln?",
  "Ich würde gern meine Überstunden ausbezahlt bekommen und nicht diese Mehrarbeit durch Freizeit ausgleichen. Wie siehst du das?",
  "Sie sind Teilnehmende eines Debattierclubs und diskutieren über die aktuelle Frage."
]

export default smalltalkQuestions.map((item) => ({ question: item, tags: undefined }))